---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3124751044-6XXjYpMckDXtH9vMMUS0j5zBAdXEuAgY13vYzOW
:access_token_secret: cRIShpgkZgmMasZmLiyttFquMfPkaMir6cbOh36g9jB5S
